import Head from "next/head";
import styles from "@/styles/Home.module.css";

import Category from "@/components/Category";
import City from "@/components/City";
import County from "@/components/County";
import ShowForm from "@/components/ShowForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.center}>
        <ShowForm />
      </div>

      {/* <div className={styles.background}>
        <div className={styles.categoryDiv}>
          <Category />
        </div>

        <div className={styles.cityDiv}>
          <City />
          <County />
        </div>
      </div> */}
    </>
  );
}
